# -*- coding: utf-8 -*-
"""Concatenate_and_eval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujZACQTZQunU-hxes6PSlSZZC_FZ7Oxs
"""

import math
import torch
import json
import numpy as np
import pandas as pd
print(pd.__version__)
import tensorflow as tf
print(tf.__version__)
from transformers import TFBertModel #do I actually need these? Yes
from transformers import BertTokenizer #do I actually need these? Yes
from transformers import BertConfig
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_model = TFBertModel.from_pretrained("bert-base-uncased")
bert_config = BertConfig.from_pretrained('bert-base-uncased')
from sklearn.linear_model import LogisticRegression as lg #Dr Stine recommended this classifier model in place of AutoModelforSequenceClassification
from sklearn.pipeline import Pipeline as pipe #CHATGPT recommended this when I asked about other useful sklearn tools that would be useful for LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score
from sklearn.preprocessing import StandardScaler #CHATGPT recommended this when I asked about other useful sklearn tools that would be useful for LogisticRegression


def get_x_for_sklearns(concatenated_set):
  print("takes concatenated_set, makes it a numpy, then shoves in a thing called x (no relation to Elon the fascist) \n")
  #by the way, the concatenated_set is a 2 sets of cls_embeds paired together
  print("in America, you learn sk, in Soviet Russia, sk learns you!!!!!\n")
  print("oh my god btw I literally forgot to do the GRE this summer, its okay though only one grad program imma apply for still requires it\n")

  x_ = []

  for i in range(len(concatenated_set)):
    x_.append(concatenated_set[i].numpy()) #list index is outta range!!!!! Syntax error as of July 25th, 2025!

  #x_ = concatenated_set.numpy()

  return x_


def get_y_for_sklearns():
  print("okay this ones is gonna be a doosy\n")
  #do I just, like, write them?
  #ternary labels!

  y_ = ["entail", "contradict", "neutral"] #these are the three possible gold_labels from the multiNLI

  return y_


def concatenate_sets(set1, set2, axial_value):
  print("Lemonade is yellow")


  if not isinstance(axial_value, int):
    print("axial value must be integer")
    return -1
  if axial_value not in (0,1):
    print("axial value must be one or zero")
    return -1

  #you CANNOT just concatenate one set onto another, you'll have to go item by item in each set for desired effect

  '''
  print(type(set1))
  print(type(set1[0]))
  print(set1[0])
  print(type(set2))
  print(type(set2[0]))
  print(set2[0])
  '''

  concatenated_set = {}

  for i in range(len(set1)):
    concatenated_set[i] = tf.concat([set1[i], set2[i]], axis = axial_value)   #should I concatenate with axis of 0 or axis of 1? Oh shit this might be the most important question of my entire life oh my god everything rides on me getting this right


  #print("concatenated set's shape")
  #print(concatenated_set.shape())
  print("concatenated set's type")
  print(type(concatenated_set))
  print("concatenated set's length")
  print(len(concatenated_set))
  print("concatenated set[0] length")
  print(len(concatenated_set[0]))
  #print("concatenated set[0]'s dtype")
  #print(concatenated_set[0].dtype())

  #print("set1 shape")
  #print(set1.shape())
  print("set1 type")
  print(type(set1))
  print("set1 length")
  print(len(set1))
  print("set1[0] length")
  print(len(set1[0]))
  #print("set1[0] dtype")
  #print(set1[0].dtype())

  #print("set2 shape")
  #print(set2.shape())
  print("set2 type")
  print(type(set2))
  print("set2 length")
  print(len(set2))
  print("set2[0] length")
  print(len(set2[0]))
  #print("set2[0] dtype")
  #print(set2.dtype())


  return concatenated_set


def import_cls_from_bin(file_import):

  print(f"Importing {file_import}.bin \n")

  tensors = []

  print(file_import)

  with tf.io.gfile.GFile(file_import + ".bin", "rb") as f:
    while True: #this makes sure to stop reading the bin file when there are no more bytes to take print("b")

      byte_length = f.read(4)
      if not byte_length:
        break


      length = int.from_bytes(byte_length, 'big')

      data = f.read(length)

      tensor = tf.io.parse_tensor(data, out_type=tf.float32)

      tensors.append(tensor)

  return tensors

def main():

  print("main function \n")



  files_names = ["P", "P_", "H", "H_", "CS1", "CS1_", "CS2", "CS2_"]

  tensor_collection = {}


  for i in files_names:
    tensor_to_append = import_cls_from_bin(i)
    tensor_collection[i] = tensor_to_append


  for i in tensor_collection:
    print(i)

    #print(tensor_collection[i][0]) //will print out CLS token of the first sentence in that set
    #print(tensor_collection[i])  // will print out CLS token of every sentence in that set


  #concatenate_sets(tensor_collection["P"], tensor_collection["H_"], 3.3)
  #concatenate_sets(tensor_collection["P"], tensor_collection["H_"], 3)

  #axis=0
  pcs2 = concatenate_sets(tensor_collection["P"], tensor_collection["CS2"], 0)
  p_cs2 = concatenate_sets(tensor_collection["P_"], tensor_collection["CS2"], 0)
  pcs2_ = concatenate_sets(tensor_collection["P"], tensor_collection["CS2_"], 0)
  p_cs2_ = concatenate_sets(tensor_collection["P_"], tensor_collection["CS2_"], 0)

  cs1h = concatenate_sets(tensor_collection["CS1"], tensor_collection["H"], 0)
  cs1_h = concatenate_sets(tensor_collection["CS1_"], tensor_collection["H"], 0)
  cs1h_ = concatenate_sets(tensor_collection["CS1"], tensor_collection["H_"], 0)
  cs1_h_ = concatenate_sets(tensor_collection["CS1_"], tensor_collection["H_"], 0)


  #I need to verify if these concatenated sets are actually printing the correct thing..
  #very important that I make sure that each sentence within the two sets is concatenated together
  #and not that the entirety of one set is not just tacked onto another
  #I already print out the shapes of each concatenated sets, and the shape is twice as large as the two previous sets, so I know it is concatenating correctly
  #however as an extra sanity test, you'll find it is concatenating properly

  #print first element of pcs2 concatenated set
  print("\n pcs2[0] \n") #<-- while this prints out an ammended array due to the IDE's limitations, you'll find the first element of one vectembed and the last element of the other vectembed as the first and last vectembeds elements here.
  print(pcs2[0])

  print("\n p[0] \n")
  print(tensor_collection["P"][0])

  print("\n cs2[0] \n")
  print(tensor_collection["CS2"][0])

   #Checking again just to be sure

  #print first element of pcs2 concatenated set
  print("\n cs1_h[3] \n") #<-- yep, also good!.
  print(cs1_h[3])

  print("\n cs1_[3] \n")
  print(tensor_collection["CS1_"][3])

  print("\n h[3] \n")
  print(tensor_collection["H"][3])

  #just note that in the separated sets, all the elements of the vectembeds are 10^-1, whereas in the final
  #concatenated set, they are just plain old 10^0, so don't let that surprise you if a -0.493e-1 becomes a -4.93 in the concatenated version






  #axis=1 DOING IT WITH AXIS ONE THROWS AN ERROR! >:(
  #pcs2_axis1 = concatenate_sets(tensor_collection["P"], tensor_collection["CS2"], 1)



  #get_x_for_sklearn

  a_sample_of_x = get_x_for_sklearns(pcs2)

  #get_y_for_sklearn (its literally just gold labels)
  a_sample_of_y = get_y_for_sklearns()

  print(a_sample_of_x)
  print(type(a_sample_of_x))
  print(a_sample_of_y)
  print(type(a_sample_of_x[0]))
  print(type(a_sample_of_x[0][0]))
  print(a_sample_of_x[0][0])

  #print(a_sample_of_x.shape)
  print(a_sample_of_x[0].shape)

  for i in range(len(a_sample_of_x)):
    print(a_sample_of_x[i].shape)





  #print(sklearn.get_config())

  #sklearn.linear_model.LogisticRegression.setconfig(bert_config) #July 27th 2:17AM note, I'll fix this later

  #update as of July 27, 3:48PM. Apparently I learned you can't just jam the bert_configuration into sklearn like a barbarian
  #infact you don't even jam the configs in at all.
  #Lol. weird. It's almost like reading the sklearn documentation should've been step one..
  #...before trying to willynilly use random sklearns functions like a madman


  #remember that I imported LogisticRegression as "lg"


  #okay so I just learned as of 4:24pm on July 27th, 2025, that len of x and y inputs for fit must be of equal length
  #cuz the lg classifer model uses these fit data to labels to train the model
  #and then the model will later take in another data (only an x) and try to predict how that set would..
  #.. be potentially labelled with Y, based on what the model learned from that original fit of x to y...
  #.... that the model took as gospel truth!



  classification_model = lg(random_state = 0).fit(a_sample_of_x, a_sample_of_y )
  classification_model.predict(a_sample_of_x)
  classification_model.predict_proba(a_sample_of_x)
  classification_model.score(a_sample_of_x, a_sample_of_y)










if __name__ == "__main__":
  main()

