# -*- coding: utf-8 -*-
"""File0differentAngle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hJN9pikBVwe7kXLj0qN579nsj80jFMrQ
"""

from google.colab import drive
drive.mount('/content/drive')

from dataclasses import dataclass
from copy import deepcopy
import pickle
import math
import torch
import json
import os
import gc
import numpy as np
import pandas as pd
import tensorflow as tf
from transformers import TFBertModel
from transformers import BertTokenizer

# Load the tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_model = TFBertModel.from_pretrained("bert-base-uncased", from_pt = True)

#check if Tensorflow is finding the GPU's
print(tf.config.list_physical_devices('GPU'))


# Test tokenization
text = "Hello, TensorFlow!"
tokens = tokenizer.encode(text, return_tensors="tf")  # Use "tf" instead of "pt" for TensorFlow tensors


#_____________________________________#



def prep_data():
  print("prep data")
  #name of the multinli jsonl file
  file_name = "multinli_1.0_dev_matched.jsonl"
  path = "/content/drive/MyDrive/Colab Notebooks/DataforFile0differentAngle"
  #https://pandas.pydata.org/docs/reference/api/pandas.read_json.html  I can read this shit line by line with pandas

  entries_full = pd.read_json(path + '/' + file_name, lines = True, encoding = "utf-8")
  cols = entries_full.columns
  print(f"name of variables: {cols}")
  variables_needed = ['gold_label', 'sentence1', 'sentence2']

  #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.copy.html

  entries = entries_full[variables_needed].copy(deep=True)
  print(entries)
  return entries

def tokenized_data(entries, tokenizer):
  print("tokenize data")
  s1_tok = []
  s2_tok = []

  #https://www.w3schools.com/python/pandas/ref_df_iterrows.asp
  for i, entry in entries.iterrows():
    s1_tok.append(tokenizer.encode(entry['sentence1'], return_tensors = "tf"))
    s2_tok.append(tokenizer.encode(entry['sentence2'], return_tensors = "tf"))

  entries['s1_tok'] = s1_tok
  entries['s2_tok'] = s2_tok

  print(entries)

def desired_removals(tokenizer):
   #for now this is hard_coded in, later I want this to be a text file that you can insert for custom words
  print("desired words to be removed")

  words_to_remove = ["on top", "in front", "next to",
    "in", "out", "over", "under", "above", "below", "inside",
    "outside", "around", "behind", "on", "near", "through",
    "throughout", "beneath", "into", "beside", "off", "between",
    "next", "upon", "from"]

  #as of 12/18/2025, I realize that multiword prepositions must go first. Otherwise, they get clipped.

  words_remove_tok_ids = [tokenizer.encode(word, add_special_tokens = False) for word in words_to_remove]
  print("Token Ids of words to remove: ", words_remove_tok_ids)
  return words_remove_tok_ids

def find_removals(entries, to_remove):
  print("finding sentences to remove")
  #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html we can drop rows via axis=0

  #for eeach row of s1, gonna have to make a copy, flatten the copy,
  #search it for matching tokens, note row nums, then use row nums to drop from original panda df
  s1_tok = entries["s1_tok"]
  print(type(s1_tok))
  print(s1_tok)

  def flattening_to_tok(s1_tok):
    print("flattening copy of s1")
    s1_flat = []
    for entry in s1_tok:
      s1_flat.append(s1_tok.to_numpy().flatten().tolist())
    return s1_flat

  def finder(s1_flat, to_remove):

    def word_search(entry, to_remove):
      sent1_has_word = False
      #10/29/25 update, adding it infrastructure for subtokens
      def contains_sequence(tokens, sequence):
        for seq in sequence:
          n = len(seq)
          for i in range(len(tokens) - n + 1):
            if tokens[i:i+n] == seq:
              return True
        return False

      sent1_has_word = contains_sequence(entry, to_remove)
      return sent1_has_word

    counter_s1 = 0
    row_tracker = []

    for i, entry in s1_flat.iterrows():
      s1_has = word_search(entry, to_remove)
      if s1_has:
        counter_s1 += 1
        #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.index.html
        #https://www.reddit.com/r/learnpython/comments/4c6bjc/getting_the_index_number_of_a_specific_row_pandas/
        #this should give me the index of any rows in the dataframe that are identified as having my desired removals
        row_tracker.append(s1_flat.index[i])

    return row_tracker, counter_s1


  def cull_data(entries, row_tracker):
    #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html
    #use iloc to save just some indexes iloc = index location
    #better stratiegy would be to remove the rows we don't need
    #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html
    for i, entry in entries.iterrows():
      if i not in row_tracker:
        entries.drop([i])

  s1_flat = flattening_to_tok(s1_tok)
  row_tracker, counter_s1 = finder(s1_flat, to_remove)
  cull_data(entries, row_tracker)
  return counter_s1, row_tracker



def main():
  print("start of program")
  entries = prep_data()
  tokenized_data(entries, tokenizer)
  to_remove = desired_removals(tokenizer)
  counter_s1, row_tracker = find_removals(entries, to_remove)
  print(entries.shape)
  print(f"Counter S1: {counter_s1},\n row_tracker: {row_tracker}")
  print(entries)

if __name__ == "__main__":
  main()