# -*- coding: utf-8 -*-
"""FineTuneBertInstead.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nZrAslZhs83pOR9_bU1o1RrnMlmB989s
"""

from google.colab import drive
drive.mount('/content/drive')

'''
Kyle Urban Capstone
We are trying one final time here completely fresh
1. run this on regular data set (small test)
2. run this on regular data set (full test)
3. run this on modified data set (full test)
4. compare results
'''
#https://huggingface.co/docs/datasets/en/about_map_batch

from datasets import Dataset
import numpy as np
import pandas as pd
import torch
from transformers import (
    BertTokenizer,
    BertForSequenceClassification,
    Trainer,
    TrainingArguments
)




def data_prepare():
  print("prepare data")
  #name of the multinli jsonl file
  file_name = "multinli_1.0_dev_matched.jsonl"
  path = "/content/drive/MyDrive/Colab Notebooks/DataforFineTuneBertInstead"
  #https://pandas.pydata.org/docs/reference/api/pandas.read_json.html  I can read this shit line by line with pandas

  entries_full = pd.read_json(path + '/' + file_name, lines = True, encoding = "utf-8")
  cols = entries_full.columns
  print(f"name of variables: {cols}")
  variables_needed = ['gold_label', 'sentence1', 'sentence2']

  #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.copy.html

  entries = entries_full[variables_needed].copy(deep=True)
  print(entries)
  return entries

def filter_out_hyphen_labels(entries):
  #note that in the MultiNLI, there is a hyphen gold label as well
  print("filtering hyphens")
  #https://stackoverflow.com/questions/73907106/pandas-remove-every-entry-with-a-specific-value
  #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html
  #https://pandas.pydata.org/docs/user_guide/indexing.html
  print("Unique labels found:", entries['gold_label'].unique())


  entries = entries[entries['gold_label'] != '-']
  return entries

def gold_label_to_integers(entries):
  print("map gold_labels to integers")
  label_map = {'entailment': 0, 'neutral': 1, 'contradiction': 2}
  entries['label'] = entries['gold_label'].map(label_map)

  #https://pandas.pydata.org/docs/reference/api/pandas.Index.dropna.html
  entries = entries.dropna(subset=['label'])
  #make sure every label is now an integer
  entries['label'] = entries['label'].astype(int)
  return entries


def experiment(entries):
  print("experiment")

  #https://stackoverflow.com/questions/73154119/how-do-i-convert-pandas-dataframe-to-a-huggingface-dataset-object
  dataset = Dataset.from_pandas(entries)


  dataset = dataset.train_test_split(test_size=0.1)
  train_dataset = dataset["train"]
  eval_dataset = dataset["test"]
  print("train_test_split done")

  #https://huggingface.co/docs/datasets/v1.8.0/processing.html
  tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

  #sentence1 = premise
  #sentence2 = hypothesis

  # This concatenates sentence 1 and 2 as a single sequence before getting the CLS embedding.
  def tokenize(batch):
      return tokenizer(
          batch["sentence1"],
          batch["sentence2"],
          truncation=True,
          padding="max_length",
          max_length=128
      )

  #https://huggingface.co/docs/datasets/en/about_map_batch
  train_dataset = train_dataset.map(tokenize, batched=True)
  eval_dataset = eval_dataset.map(tokenize, batched=True)
  print("eval and train mapping done")

  # set pytorch format:
  columns = ["input_ids", "attention_mask", "token_type_ids", "label"]
  train_dataset.set_format(type="torch", columns=columns)
  eval_dataset.set_format(type="torch", columns=columns)
  print("pytorch format made")


  # Now for fine-tuning bert:
  model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=3)
  print("model created")

  ''' comment this out just to see what happens
  # Freeze bottom N encoder layers (e.g., first 8). This means only the last 4 layers of the model will update.
  for layer in model.bert.encoder.layer[:8]:
    for param in layer.parameters():
        param.requires_grad = False
  '''

  print("layers frozen")

  # Training configuration for colab:
  training_args = TrainingArguments(
      output_dir="./results",
      eval_strategy="epoch",   #evaluation_strategy got renamed to eval_strategy as per https://github.com/kubeflow/trainer/issues/2162
      save_strategy="epoch",
      learning_rate=2e-5,
      per_device_train_batch_size=16,
      per_device_eval_batch_size=16,
      num_train_epochs=3,
      weight_decay=0.01,
      logging_steps=100,
      fp16=True,              # works well on Colab GPUs allegedly
      report_to="none")

  print("training args created")

  # Set up the trainer:
  trainer = Trainer(
      model=model,
      args=training_args,
      train_dataset=train_dataset,
      eval_dataset=eval_dataset,
      tokenizer=tokenizer
  )

  print("trainer created")


  # Sanity check: ensure that you can overfit a small sample of the data.
  #https://huggingface.co/docs/transformers/en/main_classes/trainer

  small_train = train_dataset.select(range(20))
  trainer.train_dataset = small_train
  trainer.train()
  trainer.evaluate()
  # If this gets close to 100% accuracy, then it's safe to continue. Otherwise there may be bugs.
  print("small sample set done")



def main():
  print("main")
  entries = data_prepare()
  #https://discuss.huggingface.co/t/from-pandas-dataframe-to-huggingface-dataset/9322
  print(entries)
  entries = filter_out_hyphen_labels(entries)
  print(entries)
  gold_label_to_integers(entries)
  print(entries)

  experiment(entries)


if __name__ == "__main__":
  main()