# -*- coding: utf-8 -*-
"""Fixingit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13kRwarssiJvVy_5FYQrlL5K2RtcJHBRb
"""

# -*- coding: utf-8 -*-
"""
Kyle Urban
University of Central Arkansas
Capstone File #1


"""
from dataclasses import dataclass
from copy import deepcopy
import math
import torch  #May 31st, 2025 update, added in PyTorch cuz https://tenor.com/search/spongebob-i-need-it-gifs
import json
import os
import numpy as np #very important to the sanity check in part 2
import pandas as pd
#print(pd.__version__)
import tensorflow as tf
#print(tf.__version__)
from transformers import TFBertModel
from transformers import BertTokenizer

# Load the tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_model = TFBertModel.from_pretrained("bert-base-uncased", from_pt = True)  #Update as of 4/2/25 # 8/8 update, you hav eto use the from_pt = True now as Huggingface got an update

# Test tokenization
text = "Hello, TensorFlow!"
tokens = tokenizer.encode(text, return_tensors="tf")  # Use "tf" instead of "pt" for TensorFlow tensors


@dataclass
class Desword_Pairs:
  row_num: int
  sentence1_des: str
  sentence2_des: str
  gold_label: str
  tokenized_s1: any = None
  tokenized_s2: any = None
  flatten_tok_s1: any = None
  flatten_tok_s2: any = None
  pad_flat_tok_s1: any = None
  pad_flat_tok_s2: any = None
  pad_tensorized_s1: any = None
  pad_tensorized_s2: any = None
  embed_s1: any = None
  embed_s2: any = None
  last_hid_state_s1: any = None
  last_hid_state_s2: any = None
  cls_embed_1: any = None
  cls_embed_2: any = None


  def __init__(self, row_num ,sentence1_des ,sentence2_des ,  gold_label , tokenized_s1 ,   tokenized_s2 ,
               flatten_tok_s1 ,  flatten_tok_s2 ,  pad_flat_tok_s1 ,  pad_flat_tok_s2 ,
               pad_tensorized_s1 ,  pad_tensorized_s2 ,  embed_s1 ,  embed_s2 , last_hid_state_s1 ,
               last_hid_state_s2 ,  cls_embed_1 , cls_embed_2):
    self.row_num = row_num
    self.sentence1_des = sentence1_des
    self.sentence2_des = sentence2_des
    self.gold_label = gold_label
    self.tokenized_s1 = tokenized_s1
    self.tokenized_s2 = tokenized_s2
    self.flatten_tok_s1 = flatten_tok_s1
    self.flatten_tok_s2 = flatten_tok_s2
    self.pad_flat_tok_s1 = pad_flat_tok_s1
    self.pad_flat_tok_s2  = pad_flat_tok_s2
    self.pad_tensorized_s1 = pad_tensorized_s1
    self.pad_tensorized_s2  = pad_tensorized_s2
    self.embed_s1 = embed_s1
    self.embed_s2 = embed_s2
    self.last_hid_state_s1 = last_hid_state_s1
    self.last_hid_state_s2 = last_hid_state_s2
    self.cls_embed_1 = cls_embed_1
    self.cls_embed_2 = cls_embed_2



@dataclass #this makes the __init__ and __repr__ functions for me :)  (took this line from ChatGPT)
class MultiNLI_entry:
  row_num: int
  sentence1: str
  sentence2: str
  gold_label: str
  tokenized_s1: any = None
  tokenized_s2: any = None
  flatten_tok_s1: any = None
  flatten_tok_s2: any = None
  pad_flat_tok_s1: any = None
  pad_flat_tok_s2: any = None
  pad_tensorized_s1: any = None
  pad_tensorized_s2: any = None
  embed_s1: any = None
  embed_s2: any = None
  last_hid_state_s1: any = None
  last_hid_state_s2: any = None
  cls_embed_1: any = None
  cls_embed_2: any = None


  def flatten_tf_to_list(self):
    self.flatten_tok_s1 = self.tokenized_s1.numpy().flatten().tolist() #each line gets flattened
    self.flatten_tok_s2 = self.tokenized_s2.numpy().flatten().tolist() #each line gets flattened

  def word_search(self, words_remove_tok_ids):
    sent1_has_word = False
    sent2_has_word = False

    removal_set = set(words_remove_tok_ids)
    for token in self.flatten_tok_s1:
      if token in removal_set:
        sent1_has_word = True

    for token in self.flatten_tok_s2:
      if token in removal_set:
        sent2_has_word = True

    return sent1_has_word, sent2_has_word

  def copy_to_desword_pair(self):
    copied = deepcopy(self)

    return Desword_Pairs( row_num = copied.row_num,
                         sentence1_des= copied.sentence1,
                         sentence2_des = copied.sentence2,
                         gold_label = copied.gold_label,
                         tokenized_s1 = copied.tokenized_s1,
                         tokenized_s2 = copied.tokenized_s2,
                         flatten_tok_s1 = copied.flatten_tok_s1,
                         flatten_tok_s2 = copied.flatten_tok_s2,
                         pad_flat_tok_s1 = copied.pad_flat_tok_s1,
                         pad_flat_tok_s2 = copied.pad_flat_tok_s2,
                         pad_tensorized_s1 = copied.pad_tensorized_s1,
                         pad_tensorized_s2 = copied.pad_tensorized_s2,
                         embed_s1 = copied.embed_s1,
                         embed_s2 = copied.embed_s2,
                         last_hid_state_s1 = copied.last_hid_state_s1,
                         last_hid_state_s2 = copied.last_hid_state_s2,
                         cls_embed_1 = copied.cls_embed_1,
                         cls_embed_2 = copied.cls_embed_2  )

#gonna have a desword pairs that stores the sentence 1's with preps and the sentence 2 that matches to them
#basically the P --> CS2 and variations of
#the another that has the sentence 2's and the sentence 1 that matches to them
#basically the CS1 --> H and variations of
#the removal of preps (or other words) shall take place as an external functions, and the variations of the pairs
#shall be stored as such in the sentence1_des and sentence2_des of appropriately labeled arrays of objects



def prep_data():
    print("prep data")

    #name of the multinli jsonl file
    file_name = "multinli_1.0_dev_matched.jsonl"

    entries = []

    with open(file_name, "r", encoding="utf=8") as file:
      for index, line in enumerate(file):
        data_line = json.loads(line)
        entry = MultiNLI_entry(
            row_num = index,
            sentence1 = data_line.get("sentence1", ""),
            sentence2 = data_line.get("sentence2", ""),
            gold_label = data_line.get("gold_label", ""),
        )

        entries.append(entry)

    return entries

#I could have made this a method
def tokenize_data(entries, tokenizer):
  print("tokenize data")

  for entry in entries:
    entry.tokenized_s1 = tokenizer.encode(entry.sentence1, return_tensors = "tf")
    print(entry.tokenized_s1)
    entry.tokenized_s2 = tokenizer.encode(entry.sentence2, return_tensors = "tf")
    print(entry.tokenized_s2)

def flatten_data(entries, tokenizer):
  print("calls class MultiNLI method to flatten data")

  for entry in entries:
    entry.flatten_tf_to_list()
    #print(type(entry.flatten_tok_s1))
    #print(type(entry.flatten_tok_s2))


def desired_words_to_remove(tokenizer):
  #for now this is hard_coded in, later I want this to be a text file that you can insert for custom words
  print("desired words to be removed")

  words_to_remove = ["above", "below", "behind", "inside", "outside"]

  words_remove_tok_ids = [tokenizer.encode(word, add_special_tokens = False)[0] for word in words_to_remove]

  print("Token Ids of words to remove: ", words_remove_tok_ids)
  return words_remove_tok_ids



  #finish this later

  #remove_words_token_ids = {key: tokenizer.encode(key, add_special_tokens = False)}


def find_sentences_with_only_desired_words_to_remove(words_remove_tok_ids, all_nli_entries):
  print("this should find only the sentences with the desired words to remove and store them in an new array of MultiNLI classes")
  #entries but only the entries that contain the desired words to be removed
  entries_deswords_s1 = [] #where s1 has the entries we want and s2 is just along for ride
  entries_deswords_s2 = [] #where s2 has the entries we want and s1 is just along for ride

  counter_s1 = 0
  counter_s2 = 0

  #marks true or false for any entry in all the nli data if there is a sentence with a preposition
  for entry in all_nli_entries:
    sent1_has_word, sent2_has_word = entry.word_search(words_remove_tok_ids)
    #print(sent1_has_word, sent2_has_word)


    #for the
    if sent1_has_word and not sent2_has_word:
      print("place holder")
      new_desword_pair = entry.copy_to_desword_pair() #is this how I do it? #8/15 update, I added the parenthesis and now it works
      entries_deswords_s1.append(new_desword_pair)
      #deep copy any sent1 with words to desword pair
      counter_s1 += 1


    if sent2_has_word and not sent1_has_word:
      print("place holder")
      new_desword_pair = entry.copy_to_desword_pair()
      entries_deswords_s2.append(new_desword_pair)
      #deep copy any sent2 with words to desword pair
      counter_s2 += 1


  #as a test
  print(" p --> cs2")
  print(entries_deswords_s1[0])
  print(" cs1 --> h")
  print(entries_deswords_s2[0])

  print("counter_s1: ",  counter_s1 )
  print("counter_s2: ",  counter_s2)





def main():
  print("start of program")
  all_nli_entries = prep_data()
  print(all_nli_entries)
  #tokenize_data function returns a tensorflow tensor
  tokenize_data(all_nli_entries, tokenizer)
  #remember that all_nli_entries is all 10000 sentences, if we are gonna search and rip prepositions
  #we need have two functions that search those, put them into another class MultiNLI, then another function to
  #search and destroy the preps. Has to happen between tokenize and tensorize steps
  #the cls embeds for all the tensorized data could be used as training data over in the other file?
  flatten_data(all_nli_entries, tokenizer)
  words_remove_tok_ids = desired_words_to_remove(tokenizer)

  print(all_nli_entries[0])
  #pad after finding and removing
  find_sentences_with_only_desired_words_to_remove(words_remove_tok_ids, all_nli_entries)





if __name__ == "__main__":
  main()