# -*- coding: utf-8 -*-
"""ImportPickleConcateEval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vRgWf5VpWdEIvCpAKG-SmOXZnuiYr_O7
"""

from google.colab import drive
drive.mount('/content/drive')

# -*- coding: utf-8 -*-
"""
Kyle Urban
University of Central Arkansas
Capstone File #1


"""
from dataclasses import dataclass
from copy import deepcopy
import pickle
import math
import torch  #May 31st, 2025 update, added in PyTorch cuz https://tenor.com/search/spongebob-i-need-it-gifs
import json
import os
import numpy as np #very important to the sanity check in part 2
import pandas as pd
#print(pd.__version__)
import tensorflow as tf
#print(tf.__version__)
from transformers import TFBertModel
from transformers import BertTokenizer

# Load the tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_model = TFBertModel.from_pretrained("bert-base-uncased", from_pt = True)  #Update as of 4/2/25 # 8/8 update, you hav eto use the from_pt = True now as Huggingface got an update


from transformers import BertConfig
bert_config = BertConfig.from_pretrained('bert-base-uncased')
from sklearn.linear_model import LogisticRegression as lg #Dr Stine recommended this classifier model in place of AutoModelforSequenceClassification
from sklearn.pipeline import Pipeline as pipe #CHATGPT recommended this when I asked about other useful sklearn tools that would be useful for LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score
from sklearn.preprocessing import StandardScaler #CHATGPT recommended this when I asked about other useful sklearn tools that would be useful for LogisticRegression
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import LabelEncoder    #10/18/2025 Borrowed from ChatGPT (I have to make the gold labels numbers)


from numpy import mean
from numpy import absolute



#gonna use StratifiedKFold because I have no clue if the gold_labels are proportional to each other in the MultiNLI data


#move model onto GPU runtime to go faster (9/3/2025 update, ya' know ya boi got that google colabs pro)
''' #this is for pytorch only, tensorflow does this automatically
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
bert_model.to(device)
'''
#check if Tensorflow is finding the GPU's

print(tf.config.list_physical_devices('GPU'))



# Test tokenization
text = "Hello, TensorFlow!"
tokens = tokenizer.encode(text, return_tensors="tf")  # Use "tf" instead of "pt" for TensorFlow tensors


@dataclass
class Desword_Pairs:
  row_num: int
  sentence1_des: str
  sentence2_des: str
  gold_label: str
  tokenized_s1: any = None
  tokenized_s2: any = None
  flatten_tok_s1: any = None
  flatten_tok_s2: any = None
  pad_flat_tok_s1: any = None
  pad_flat_tok_s2: any = None
  tensorized_s1: any = None
  tensorized_s2: any = None
  pad_tensorized_s1: any = None
  pad_tensorized_s2: any = None
  embed_s1: any = None
  embed_s2: any = None
  last_hid_state_s1: any = None
  last_hid_state_s2: any = None
  cls_embed_1: any = None
  cls_embed_2: any = None


  def __init__(self, row_num ,sentence1_des ,sentence2_des ,  gold_label , tokenized_s1 ,   tokenized_s2 ,
               flatten_tok_s1 ,  flatten_tok_s2 ,  pad_flat_tok_s1 ,  pad_flat_tok_s2 , tensorized_s1, tensorized_s2,
               pad_tensorized_s1 ,  pad_tensorized_s2 ,  embed_s1 ,  embed_s2 , last_hid_state_s1 ,
               last_hid_state_s2 ,  cls_embed_1 , cls_embed_2):
    self.row_num = row_num
    self.sentence1_des = sentence1_des
    self.sentence2_des = sentence2_des
    self.gold_label = gold_label
    self.tokenized_s1 = tokenized_s1
    self.tokenized_s2 = tokenized_s2
    self.flatten_tok_s1 = flatten_tok_s1
    self.flatten_tok_s2 = flatten_tok_s2
    self.pad_flat_tok_s1 = pad_flat_tok_s1
    self.pad_flat_tok_s2  = pad_flat_tok_s2
    self.tensorized_s1 = tensorized_s1
    self.tensorized_s2 = tensorized_s2
    self.pad_tensorized_s1 = pad_tensorized_s1
    self.pad_tensorized_s2  = pad_tensorized_s2
    self.embed_s1 = embed_s1
    self.embed_s2 = embed_s2
    self.last_hid_state_s1 = last_hid_state_s1
    self.last_hid_state_s2 = last_hid_state_s2
    self.cls_embed_1 = cls_embed_1
    self.cls_embed_2 = cls_embed_2

#the Desword_pair object also needs it own flatten to list obbject
#may not actually need this object
  def flatten_tf_to_list(self):
    self.flatten_tok_s1 = self.tokenized_s1.numpy().flatten().tolist() #each line gets flattened
    self.flatten_tok_s2 = self.tokenized_s2.numpy().flatten().tolist() #each line gets flattened

  def convert_back_to_tensors(self):
    print("takes flattened tensors and makes them unflat")

    self.tensorized_s1 = tf.reshape(tf.convert_to_tensor(self.flatten_tok_s1, dtype=tf.int32), (1, len(self.flatten_tok_s1)))
    self.tensorized_s2 = tf.reshape(tf.convert_to_tensor(self.flatten_tok_s2, dtype=tf.int32), (1, len(self.flatten_tok_s2)))


  def pad_tensors(self, max_seq_len_ten_s1, max_seq_len_ten_s2):
    print("post pads all my tensors")



    self.pad_tensorized_s1 = tf.keras.preprocessing.sequence.pad_sequences(self.tensorized_s1, maxlen = max_seq_len_ten_s1, padding = "post")
    self.pad_tensorized_s2 = tf.keras.preprocessing.sequence.pad_sequences(self.tensorized_s2, maxlen = max_seq_len_ten_s2, padding = "post")
    #https://www.tensorflow.org/api_docs/python/tf/keras/utils/pad_sequences
    #rework the code here to get a maximum lenght atwhich the sequences can be padded 8/24/2025

    print("row number: ", self.row_num)
    print("pad_tensorized_s1: ", self.pad_tensorized_s1)
    print("pad_tensorized_s2: " , self.pad_tensorized_s2)


  def get_shape_tok_s1(self):
    return self.tokenized_s1.shape

  def get_shape_tok_s2(self):
    return self.tokenized_s2.shape

  def get_shape_tensorized_s1(self):
    return self.tensorized_s1.shape

  def get_shape_tensorized_s2(self):
    return self.tensorized_s2.shape

  def get_shape_pad_ten_s1(self):
    return self.pad_tensorized_s1.shape

  def get_shape_pad_ten_s2(self):
    return self.pad_tensorized_s2.shape

  def get_last_hid_state_shape_s1(self):
    return self.last_hid_state_s1.shape

  def get_last_hid_state_shape_s2(self):
    return self.last_hid_state_s2.shape


#necesary for the word_search and removal method
  def copy_deep(self):
    return deepcopy(self)

  def word_search_and_remove(self, words_remove_tok_ids):
    print(self.row_num)

    #gonna have to do this 3 times. Once for modifying the p/cs1, once for modifying the h/cs2, and then once for both modified
    #this should return 6 sets total I believe

    #in order to do this imma need to make deep copies of every self (every entry) 3 times inside here.

    #removing from the deep copied sets
    removal_set = set(words_remove_tok_ids)


    #https://realpython.com/python-enumerate/
    #https://www.w3schools.com/python/ref_list_pop.asp
    #https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions
    #https://stackoverflow.com/questions/1207406/how-to-remove-items-from-a-list-while-iterating



    #Will the number of sentences that had a preposition removed be the same as the number of sentences that had a prepositions spotted?
    #go over your code logic with Dr Stine.


    #p' --> cs2 and cs1' --> h
    self_s1mod = self.copy_deep()
    self_s1mod.flatten_tok_s1 = [token for token in self.flatten_tok_s1 if token not in removal_set]


    #makes sense because when working cs1h, not all cs1s will have preps
    if (len(self_s1mod.flatten_tok_s1) == len(self.flatten_tok_s1)):
      print("len of s1  ")
      print(len(self.flatten_tok_s1))
      print("len of s1' ")
      print(len(self_s1mod.flatten_tok_s1))

    #p --> cs2' and cs1 --> h'
    self_s2mod = self.copy_deep()
    self_s2mod.flatten_tok_s2 = [token for token in self.flatten_tok_s2 if token not in removal_set]

    #makes sense because when working on pcs2, not all cs2s will have preps
    if (len(self_s2mod.flatten_tok_s2) == len(self.flatten_tok_s2)):
      print("len of s2  ")
      print(len(self.flatten_tok_s2))
      print("len of s2' ")
      print(len(self_s2mod.flatten_tok_s2))


    #p'--> cs2' and cs1' --> h'
    self_bothmod = self.copy_deep()
    self_bothmod.flatten_tok_s1 = [token for token in self.flatten_tok_s1 if token not in removal_set]
    self_bothmod.flatten_tok_s2 = [token for token in self.flatten_tok_s2 if token not in removal_set]







    return self_s1mod, self_s2mod, self_bothmod




  def embed_the_padded_tensors(self):

    self.embed_s1 = bert_model(self.pad_tensorized_s1)
    self.embed_s2 = bert_model(self.pad_tensorized_s2)


  def last_hid_state_from_embed(self):

    self.last_hid_state_s1 = self.embed_s1.last_hidden_state
    self.last_hid_state_s2 = self.embed_s1.last_hidden_state

  def cls_embed_from_last_hid_state(self):

    self.cls_embed_1 = self.last_hid_state_s1[:,0,:]
    self.cls_embed_2 = self.last_hid_state_s2[:,0,:]


  def get_cls_embeds_s1(self):
    return self.cls_embed_1

  def get_cls_embeds_s2(self):
    return self.cls_embed_2

  def get_cls_embeds_rownum(self):
    return self.row_num, self.cls_embed_1, self.cls_embed_2


  #https://arxiv.org/pdf/1705.02364
  #this article (page 3) explains why I need to use this
  #returns a tuple with the row_num, a concatenation of (cls1, cls2, element difference of cls1 and cls2, element wise product of cls1 and cls2) and the gold label
  def get_cls_embeds_rownum_concate_gold(self):
    #print(type(self.cls_embed_1), type(self.cls_embed_2)) #<--- these are tensorflow tensors
    cls1 = self.cls_embed_1.numpy()   #converts to numpy (cuz sk learns expects that )
    cls2 = self.cls_embed_2.numpy()
    #print("cls1 and cls2 shape: ")
    #print(cls1.shape)
    #print(cls2.shape)
    #axis = 1 is very important here because it keeps the dimensions of the matrices consistent (row-wise)
    #as everything is squished from R2 to R1  10/5/2025 110:4pm update
    combo = np.concatenate((cls1, cls2, np.abs(cls1 - cls2), cls1 * cls2), axis = 1)  #<--- most important line of code here!
    combo = combo[0] #<--- second most important line of code here flattens from R2 to R1 while preserving datat (gets rid of a batch dimesion of (1,n) to just (n,))
    return self.row_num, combo, self.gold_label

  def get_cls_embeds_no_elemdiffpair(self):
    cls1 = self.cls_embed_1.numpy()   #converts to numpy (cuz sk learns expects that )
    cls2 = self.cls_embed_2.numpy()
    #print("cls1 and cls2 shape: ")
    #print(cls1.shape)
    #print(cls2.shape)
    combo = np.concatenate((cls1, cls2), axis = 1)   #should axis=1 done here since nothing
    #print(combo.shape)
    combo = combo[0]
    #print(combo.shape)
    return self.row_num, combo, self.gold_label










# ___________________________________________________________________________
# ___________________________________________________________________________
# __________________________________________________________________________

def loadData(file_name):
  path = "/content/drive/MyDrive/Colab Notebooks/DataforImportConcateEval"
  #/content/drive/MyDrive/Colab Notebooks/DataforImportConcateEval/p_cs2.pkl
  #/content/drive/MyDrive/Colab Notebooks/DataforImportConcateEval/pcs2.pkl
  dbfile = open(path + '/' + file_name, 'rb')
  db = pickle.load(dbfile)
  dbfile.close
  return db

def pull_CLS(data_set):
  cls_data_set = []
  for entry in data_set:
    cls_data_set.append(entry.get_cls_embeds_rownum_concate_gold())
  return cls_data_set

#10/18/2025 we gonna add this to see if works now.
def pull_CLS_no_elemdiffpair(data_set):
  cls_data_set = []
  for entry in data_set:
    cls_data_set.append(entry.get_cls_embeds_no_elemdiffpair())
  return cls_data_set

def get_features_labels_ids(data_set): #features are the X, labels are the y, needed for sklearns training
  print("p")
  all_rownums = []   #the rownums
  all_features = []    #the cls combo
  all_labels = []     #the gold label

  for row in data_set:
    row_num, feature, label = row  #unpacks the tuple (literally, I had no clue I could do this)
    all_rownums.append(row_num)
    all_features.append(feature)
    all_labels.append(label)

  return all_rownums, all_features, all_labels  #shall be mapped properly


def mapping_checker(data_set, X, all_rownums, y):#will check shape by making sure that shape of X(i) = shape of pcs2(1)(i) and that row_num(i) = pcs2(2)(i)
  print("t")

  for i, (orig_rownum, orig_feature, orig_label) in enumerate(data_set):

    #makes sure row ids are in order
    if all_rownums[i] != orig_rownum:
      print(f"Row ID mismatch at index {i}: {all_rownums[i]} != {orig_rownum}")
    #checks to make sure features are properly mapped by looking at shape
    if not np.array_equal(X[i], orig_feature):
       print(f"THE CLSes ARE MISMATCHED!!!!!!!!!!!!!!!!!!!!!!! AT INDEX {i}")
    if not np.array_equal(y[i], orig_label):
      print(f"THE labels ARE MISMATCHED!!!!!!!!!!!!!!!!!!!!!!! AT INDEX {i}")

#takes the row ids of the original_data and the modified data
#then compares the two and checks which ones exist in the other
#then it goes and makes an new row_nums index that includes only a subset of row_nums in the og that DO NOT appear in modified row num list
#then it uses that new row_nums index as the mask to avoid training the sklearns on data that it should be tested on
#because og is for training, mod is for testing
#so og - mod = mask and mask is used for the training.
#https://www.programiz.com/python-programming/numpy/boolean-indexing
def masking_to_remove_hyphen_goldlabel(rows, features, labels):
  print("placeholder")

  rows = np.stack(rows)
  features = np.stack(features)
  labels = np.stack(labels)


  mask = (labels != '-')
  rows = rows[mask]
  features = features[mask]
  labels  = labels[mask]

  return rows, features, labels


'''
def masker_to_get_training_data(rows_og, rows_mod, features_og, labels_og):
  mask = ~np.isin(rows_og, rows_mod)
  features_og = np.stack(features_og)  #converts list of np arrays to 2d np array to make it so I can use the mask iterator
  labels_og = np.stack(labels_og)
  rows_og = np.stack(rows_og)


  Xtrain = features_og[mask]
  ytrain = labels_og[mask]
  rowtrain = rows_og[mask]

  return Xtrain, ytrain, rowtrain
'''
'''
#this trains the kfold classifier model X is the train features, y is the train labels, k is the number of folds
def train_stratifiedkfold_classifier_model(X, y, k):
  print("o")
  stratkfold = StratifiedKFold(n_splits = k, shuffle = True, random_state = 42)  #why the fuck does every online example use 42?
  accuracies = []
  f1s = []

  for fold, (train_index, eval_index) in enumerate(stratkfold.split(X, y)):
    X_train, X_eval = X[train_index], X[eval_index]
    y_train, y_eval = y[train_index], y[eval_index]

    #lg = logistic regression

    #teh logistic regression model itself
    classification_model = lg(max_iter = 1000)
    classification_model.fit(X_train, y_train)
    y_pred = classification_model.predict(X_eval)
    #this takes the model that was just trained, and makes it take a test. y_eval is the answer key, y_pred is the test
    accuracy = accuracy_score(y_eval, y_pred)
    f1 = f1_score(y_eval, y_pred, average = "weighted")

    accuracies.append(accuracy)
    f1s.append(f1)

  return classification_model, accuracies, f1s

'''

def label_encode(labels):
  print(type(labels[0]))
  le = LabelEncoder()
  labels_encoded = le.fit_transform(labels)
  print(type(labels_encoded[0]))
  return labels_encoded


def LOOCV_eval(model, X, y, scoring_method, cv):
  scores = cross_val_score(model, X, y, scoring = scoring_method, cv = cv , n_jobs= -1)
  print(scores)
  return np.mean(scores)  #gonna do the np.mean instead  10/18/2025 at 3:08pm


def main():
  #loads the data from the pickle files
  print("ha")
  pcs2 = loadData("pcs2.pkl")
  p_cs2 = loadData("p_cs2.pkl")
  #og_set_partial = loadData("og_set.pkl")    #as of 10/5/2025, this is just the partial 500

  print(len(pcs2))
  print(len(p_cs2))


  #concatenates the data
  ''' as of 11/4/2025, turing this off so I can reduce the time it takes to calculate
  e_pcs2 = pull_CLS(pcs2)
  print("\n-----\n")
  e_p_cs2 = pull_CLS(p_cs2)
  '''
  #e_og_p = pull_CLS(og_set_partial)
  #print("length of the og_set_partial:")
  #print((len(og_set_partial)))

  noe_pcs2 = pull_CLS_no_elemdiffpair(pcs2)
  noe_p_cs2 = pull_CLS_no_elemdiffpair(p_cs2)


  '''
  print(e_pcs2[0])
  print(e_p_cs2[0])
  '''
  #print(e_og_p[0])
  print(noe_pcs2[0])
  print(noe_p_cs2[0])

  '''
  row1, X1, y1 = get_features_labels_ids(e_pcs2)
  row2, X2, y2 = get_features_labels_ids(e_p_cs2)
  '''

  row3, X3, y3 = get_features_labels_ids(noe_pcs2)
  row4, X4, y4 = get_features_labels_ids(noe_p_cs2)

  #rowogp, Xogp, yogp = get_features_labels_ids(e_og_p)

  #print(type(Xogp))
  #print(type(Xogp[0]))

  '''
  mapping_checker(e_pcs2, X1, row1, y1)
  mapping_checker(e_p_cs2, X2, row2, y2)
  '''
  mapping_checker(noe_pcs2, X3, row3, y3)
  mapping_checker(noe_p_cs2, X4, row4, y4)

  '''

  print(type(row1))
  print(type(X1))
  print(type(y1))

  print(type(row1[0]))
  print(type(X1[0]))
  print(type(y1[0]))
  '''
  '''
  row1, X1, y1 = masking_to_remove_hyphen_goldlabel(row1, X1, y1)

  print(type(row1))
  print(type(X1))
  print(type(y1))

  print(type(row1[0]))
  print(type(X1[0]))
  print(type(y1[0]))



  row2, X2, y2= masking_to_remove_hyphen_goldlabel(row2, X2, y2)
  '''

  row3, X3, y3 = masking_to_remove_hyphen_goldlabel(row3, X3, y3)
  row4, X4, y4 = masking_to_remove_hyphen_goldlabel(row4, X4, y4)


  '''
  mapping_checker(e_pcs2, X1, row1, y1)
  mapping_checker(e_p_cs2, X2, row2, y2)
  mapping_checker(noe_pcs2, X3, row3, y3)
  mapping_checker(noe_p_cs2, X4, row4, y4)
  '''

  #mapping_checker(e_og_p, Xogp, rowogp, yogp)

  #Xtrain, ytrain, rowtrain = masker_to_get_training_data(rowogp, row1, Xogp, yogp)

  #is good. There are 11 that get removed from Xtrain because the are already in pcs2/p_cs2 and we want no repeats
  #print(len(Xtrain))
  #print(len(Xogp))


  #clf_model, accuracies_og, f1s_og = train_stratifiedkfold_classifier_model(Xtrain, ytrain, 5) #sets k fold value to 5


  #Going to do the LOOCV instead
  '''

  print(len(row1))
  print(len(X1))
  print(len(y1))
  '''

  print("values counter of y1 to y4")
  '''
  print(pd.Series(y1).value_counts())
  print(pd.Series(y2).value_counts())
  '''
  print(pd.Series(y3).value_counts())
  print(pd.Series(y4).value_counts())

  '''
  print(X1.shape)
  print(y1.shape)
  '''


  classification_model = lg(max_iter= 1000)
  cross_validation_method = LeaveOneOut()

  '''
  y1 = label_encode(y1)
  y2 = label_encode(y2)
  '''
  y3 = label_encode(y3)
  y4 = label_encode(y4)
  #print(y1[:10])

  #chatgpt 10/18/2025 diagnosis of variance (little to no variance = bad)  but does it really?
  '''
  print(np.mean(X1, axis=0)[:10])  # first 10 feature means
  print(np.std(X1, axis=0)[:10])   # first 10 feature stds

  print(np.mean(X2, axis=0)[:10])  # first 10 feature means
  print(np.std(X2, axis=0)[:10])   # first 10 feature stds
  '''

  print(np.mean(X3, axis=0)[:10])  # first 10 feature means
  print(np.std(X3, axis=0)[:10])   # first 10 feature stds

  print(np.mean(X4, axis=0)[:10])  # first 10 feature means
  print(np.std(X4, axis=0)[:10])   # first 10 feature stds


  '''
  mean_score_pcs2 = LOOCV_eval(classification_model, X1, y1, 'accuracy', cross_validation_method)
  print("mean_score_pcs2: ")
  print(mean_score_pcs2)


  mean_score_p_cs2 = LOOCV_eval(classification_model, X2, y2, 'accuracy', cross_validation_method)
  print("mean_score_p_cs2: ")
  print(mean_score_p_cs2)
  '''


  mean_score_noe_pcs2 = LOOCV_eval(classification_model, X3, y3, 'accuracy', cross_validation_method)
  print("mean_score_noe_pcs2: ")
  print(mean_score_noe_pcs2)

  mean_score_noe_p_cs2 = LOOCV_eval(classification_model, X4, y4, 'accuracy', cross_validation_method)
  print("mean_score_noe_p_cs2: ")
  print(mean_score_noe_p_cs2)




  #print(accuracies_og)
  #print(f1s_og)

  #gets predictions and accuracies for pcs2
  #y1_pred = clf_model.predict(X1)
  #print(accuracy_score(y1, y1_pred))
  #print(f1_score(y1, y1_pred, average = "weighted"))



  #get predictions and accuracies for p_cs2
  #y2_pred = clf_model.predict(X2)
  #print(accuracy_score(y2, y2_pred))
  #print(f1_score(y2, y2_pred, average = "weighted"))





  #mapping_checker(e_og_p, Xtrain, rowtrain, ytrain) #should intentionally fail and all failure indices match what is on row1&row2

  #mapping_checker(e_pcs2, X2, row2, y2) #this should throw errors (intentionally to test the function)






















if __name__ == "__main__":
  main()