# -*- coding: utf-8 -*-
"""ImportPickleConcateEval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vRgWf5VpWdEIvCpAKG-SmOXZnuiYr_O7
"""

# -*- coding: utf-8 -*-
"""
Kyle Urban
University of Central Arkansas
Capstone File #1


"""
from dataclasses import dataclass
from copy import deepcopy
import pickle
import math
import torch  #May 31st, 2025 update, added in PyTorch cuz https://tenor.com/search/spongebob-i-need-it-gifs
import json
import os
import numpy as np #very important to the sanity check in part 2
import pandas as pd
#print(pd.__version__)
import tensorflow as tf
#print(tf.__version__)
from transformers import TFBertModel
from transformers import BertTokenizer

# Load the tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_model = TFBertModel.from_pretrained("bert-base-uncased", from_pt = True)  #Update as of 4/2/25 # 8/8 update, you hav eto use the from_pt = True now as Huggingface got an update

#move model onto GPU runtime to go faster (9/3/2025 update, ya' know ya boi got that google colabs pro)
''' #this is for pytorch only, tensorflow does this automatically
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
bert_model.to(device)
'''
#check if Tensorflow is finding the GPU's

print(tf.config.list_physical_devices('GPU'))



# Test tokenization
text = "Hello, TensorFlow!"
tokens = tokenizer.encode(text, return_tensors="tf")  # Use "tf" instead of "pt" for TensorFlow tensors


@dataclass
class Desword_Pairs:
  row_num: int
  sentence1_des: str
  sentence2_des: str
  gold_label: str
  tokenized_s1: any = None
  tokenized_s2: any = None
  flatten_tok_s1: any = None
  flatten_tok_s2: any = None
  pad_flat_tok_s1: any = None
  pad_flat_tok_s2: any = None
  tensorized_s1: any = None
  tensorized_s2: any = None
  pad_tensorized_s1: any = None
  pad_tensorized_s2: any = None
  embed_s1: any = None
  embed_s2: any = None
  last_hid_state_s1: any = None
  last_hid_state_s2: any = None
  cls_embed_1: any = None
  cls_embed_2: any = None


  def __init__(self, row_num ,sentence1_des ,sentence2_des ,  gold_label , tokenized_s1 ,   tokenized_s2 ,
               flatten_tok_s1 ,  flatten_tok_s2 ,  pad_flat_tok_s1 ,  pad_flat_tok_s2 , tensorized_s1, tensorized_s2,
               pad_tensorized_s1 ,  pad_tensorized_s2 ,  embed_s1 ,  embed_s2 , last_hid_state_s1 ,
               last_hid_state_s2 ,  cls_embed_1 , cls_embed_2):
    self.row_num = row_num
    self.sentence1_des = sentence1_des
    self.sentence2_des = sentence2_des
    self.gold_label = gold_label
    self.tokenized_s1 = tokenized_s1
    self.tokenized_s2 = tokenized_s2
    self.flatten_tok_s1 = flatten_tok_s1
    self.flatten_tok_s2 = flatten_tok_s2
    self.pad_flat_tok_s1 = pad_flat_tok_s1
    self.pad_flat_tok_s2  = pad_flat_tok_s2
    self.tensorized_s1 = tensorized_s1
    self.tensorized_s2 = tensorized_s2
    self.pad_tensorized_s1 = pad_tensorized_s1
    self.pad_tensorized_s2  = pad_tensorized_s2
    self.embed_s1 = embed_s1
    self.embed_s2 = embed_s2
    self.last_hid_state_s1 = last_hid_state_s1
    self.last_hid_state_s2 = last_hid_state_s2
    self.cls_embed_1 = cls_embed_1
    self.cls_embed_2 = cls_embed_2

#the Desword_pair object also needs it own flatten to list obbject
#may not actually need this object
  def flatten_tf_to_list(self):
    self.flatten_tok_s1 = self.tokenized_s1.numpy().flatten().tolist() #each line gets flattened
    self.flatten_tok_s2 = self.tokenized_s2.numpy().flatten().tolist() #each line gets flattened

  def convert_back_to_tensors(self):
    print("takes flattened tensors and makes them unflat")

    self.tensorized_s1 = tf.reshape(tf.convert_to_tensor(self.flatten_tok_s1, dtype=tf.int32), (1, len(self.flatten_tok_s1)))
    self.tensorized_s2 = tf.reshape(tf.convert_to_tensor(self.flatten_tok_s2, dtype=tf.int32), (1, len(self.flatten_tok_s2)))


  def pad_tensors(self, max_seq_len_ten_s1, max_seq_len_ten_s2):
    print("post pads all my tensors")



    self.pad_tensorized_s1 = tf.keras.preprocessing.sequence.pad_sequences(self.tensorized_s1, maxlen = max_seq_len_ten_s1, padding = "post")
    self.pad_tensorized_s2 = tf.keras.preprocessing.sequence.pad_sequences(self.tensorized_s2, maxlen = max_seq_len_ten_s2, padding = "post")
    #https://www.tensorflow.org/api_docs/python/tf/keras/utils/pad_sequences
    #rework the code here to get a maximum lenght atwhich the sequences can be padded 8/24/2025

    print("row number: ", self.row_num)
    print("pad_tensorized_s1: ", self.pad_tensorized_s1)
    print("pad_tensorized_s2: " , self.pad_tensorized_s2)


  def get_shape_tok_s1(self):
    return self.tokenized_s1.shape

  def get_shape_tok_s2(self):
    return self.tokenized_s2.shape

  def get_shape_tensorized_s1(self):
    return self.tensorized_s1.shape

  def get_shape_tensorized_s2(self):
    return self.tensorized_s2.shape

  def get_shape_pad_ten_s1(self):
    return self.pad_tensorized_s1.shape

  def get_shape_pad_ten_s2(self):
    return self.pad_tensorized_s2.shape

  def get_last_hid_state_shape_s1(self):
    return self.last_hid_state_s1.shape

  def get_last_hid_state_shape_s2(self):
    return self.last_hid_state_s2.shape


#necesary for the word_search and removal method
  def copy_deep(self):
    return deepcopy(self)

  def word_search_and_remove(self, words_remove_tok_ids):
    print(self.row_num)

    #gonna have to do this 3 times. Once for modifying the p/cs1, once for modifying the h/cs2, and then once for both modified
    #this should return 6 sets total I believe

    #in order to do this imma need to make deep copies of every self (every entry) 3 times inside here.

    #removing from the deep copied sets
    removal_set = set(words_remove_tok_ids)


    #https://realpython.com/python-enumerate/
    #https://www.w3schools.com/python/ref_list_pop.asp
    #https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions
    #https://stackoverflow.com/questions/1207406/how-to-remove-items-from-a-list-while-iterating



    #Will the number of sentences that had a preposition removed be the same as the number of sentences that had a prepositions spotted?
    #go over your code logic with Dr Stine.


    #p' --> cs2 and cs1' --> h
    self_s1mod = self.copy_deep()
    self_s1mod.flatten_tok_s1 = [token for token in self.flatten_tok_s1 if token not in removal_set]


    #makes sense because when working cs1h, not all cs1s will have preps
    if (len(self_s1mod.flatten_tok_s1) == len(self.flatten_tok_s1)):
      print("len of s1  ")
      print(len(self.flatten_tok_s1))
      print("len of s1' ")
      print(len(self_s1mod.flatten_tok_s1))

    #p --> cs2' and cs1 --> h'
    self_s2mod = self.copy_deep()
    self_s2mod.flatten_tok_s2 = [token for token in self.flatten_tok_s2 if token not in removal_set]

    #makes sense because when working on pcs2, not all cs2s will have preps
    if (len(self_s2mod.flatten_tok_s2) == len(self.flatten_tok_s2)):
      print("len of s2  ")
      print(len(self.flatten_tok_s2))
      print("len of s2' ")
      print(len(self_s2mod.flatten_tok_s2))


    #p'--> cs2' and cs1' --> h'
    self_bothmod = self.copy_deep()
    self_bothmod.flatten_tok_s1 = [token for token in self.flatten_tok_s1 if token not in removal_set]
    self_bothmod.flatten_tok_s2 = [token for token in self.flatten_tok_s2 if token not in removal_set]







    return self_s1mod, self_s2mod, self_bothmod




  def embed_the_padded_tensors(self):

    self.embed_s1 = bert_model(self.pad_tensorized_s1)
    self.embed_s2 = bert_model(self.pad_tensorized_s2)


  def last_hid_state_from_embed(self):

    self.last_hid_state_s1 = self.embed_s1.last_hidden_state
    self.last_hid_state_s2 = self.embed_s1.last_hidden_state

  def cls_embed_from_last_hid_state(self):

    self.cls_embed_1 = self.last_hid_state_s1[:,0,:]
    self.cls_embed_2 = self.last_hid_state_s2[:,0,:]


  def get_cls_embeds_s1(self):
    return self.cls_embed_1

  def get_cls_embeds_s2(self):
    return self.cls_embed_2

  def get_cls_embeds_rownum(self):
    return self.row_num, self.cls_embed_1, self.cls_embed_2







# ___________________________________________________________________________
# ___________________________________________________________________________
# __________________________________________________________________________

def loadData(file_name):
  dbfile = open(file_name, 'rb')
  db = pickle.load(dbfile)
  dbfile.close
  return db



def main():
  print("ha")
  pcs2 = loadData("pcs2.pkl")
  p_cs2 = loadData("p_cs2.pkl")

  print(len(pcs2))
  print(len(p_cs2))





if __name__ == "__main__":
  main()